import { ToastContainer } from "@/components/common/toast/ToastContainer";
import "./globals.css";
import { Inter } from "next/font/google";
import "react-toastify/dist/ReactToastify.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ReactQueryProviders } from "@/lib/reactQuery";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReactQueryProviders>
      <html lang="en" className="h-full bg-white">
        <body className={"h-full " + inter.className}>
          {children}
          <ToastContainer />
        </body>
      </html>
    </ReactQueryProviders>
  );
}
